/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LogoPro: typeof import('./inertia/components/LogoPro.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parser@7.27.1_@inertiajs+vue3@2.0.8_vue@3.5.13_typescript@5.7.3___bc5a7fcb3abc4a847cdd271c57237c70/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parser@7.27.1_@inertiajs+vue3@2.0.8_vue@3.5.13_typescript@5.7.3___bc5a7fcb3abc4a847cdd271c57237c70/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UColorModeButton: typeof import('./node_modules/.pnpm/@nuxt+ui-pro@3.1.1_@babel+parser@7.27.1_@inertiajs+vue3@2.0.8_vue@3.5.13_typescript@5.7_56d7536b68ca92c8a6326a59cca0ccc2/node_modules/@nuxt/ui-pro/dist/runtime/vue/components/color-mode/ColorModeButton.vue')['default']
    UContainer: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parser@7.27.1_@inertiajs+vue3@2.0.8_vue@3.5.13_typescript@5.7.3___bc5a7fcb3abc4a847cdd271c57237c70/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UFooter: typeof import('./node_modules/.pnpm/@nuxt+ui-pro@3.1.1_@babel+parser@7.27.1_@inertiajs+vue3@2.0.8_vue@3.5.13_typescript@5.7_56d7536b68ca92c8a6326a59cca0ccc2/node_modules/@nuxt/ui-pro/dist/runtime/components/Footer.vue')['default']
    UHeader: typeof import('./node_modules/.pnpm/@nuxt+ui-pro@3.1.1_@babel+parser@7.27.1_@inertiajs+vue3@2.0.8_vue@3.5.13_typescript@5.7_56d7536b68ca92c8a6326a59cca0ccc2/node_modules/@nuxt/ui-pro/dist/runtime/components/Header.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parser@7.27.1_@inertiajs+vue3@2.0.8_vue@3.5.13_typescript@5.7.3___bc5a7fcb3abc4a847cdd271c57237c70/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    ULink: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parser@7.27.1_@inertiajs+vue3@2.0.8_vue@3.5.13_typescript@5.7.3___bc5a7fcb3abc4a847cdd271c57237c70/node_modules/@nuxt/ui/dist/runtime/inertia/components/Link.vue')['default']
    ULinkBase: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parser@7.27.1_@inertiajs+vue3@2.0.8_vue@3.5.13_typescript@5.7.3___bc5a7fcb3abc4a847cdd271c57237c70/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    UMain: typeof import('./node_modules/.pnpm/@nuxt+ui-pro@3.1.1_@babel+parser@7.27.1_@inertiajs+vue3@2.0.8_vue@3.5.13_typescript@5.7_56d7536b68ca92c8a6326a59cca0ccc2/node_modules/@nuxt/ui-pro/dist/runtime/components/Main.vue')['default']
    UPageCTA: typeof import('./node_modules/.pnpm/@nuxt+ui-pro@3.1.1_@babel+parser@7.27.1_@inertiajs+vue3@2.0.8_vue@3.5.13_typescript@5.7_56d7536b68ca92c8a6326a59cca0ccc2/node_modules/@nuxt/ui-pro/dist/runtime/components/PageCTA.vue')['default']
    UPageFeature: typeof import('./node_modules/.pnpm/@nuxt+ui-pro@3.1.1_@babel+parser@7.27.1_@inertiajs+vue3@2.0.8_vue@3.5.13_typescript@5.7_56d7536b68ca92c8a6326a59cca0ccc2/node_modules/@nuxt/ui-pro/dist/runtime/components/PageFeature.vue')['default']
    UPageHero: typeof import('./node_modules/.pnpm/@nuxt+ui-pro@3.1.1_@babel+parser@7.27.1_@inertiajs+vue3@2.0.8_vue@3.5.13_typescript@5.7_56d7536b68ca92c8a6326a59cca0ccc2/node_modules/@nuxt/ui-pro/dist/runtime/components/PageHero.vue')['default']
    UPageSection: typeof import('./node_modules/.pnpm/@nuxt+ui-pro@3.1.1_@babel+parser@7.27.1_@inertiajs+vue3@2.0.8_vue@3.5.13_typescript@5.7_56d7536b68ca92c8a6326a59cca0ccc2/node_modules/@nuxt/ui-pro/dist/runtime/components/PageSection.vue')['default']
    USeparator: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.1_@babel+parser@7.27.1_@inertiajs+vue3@2.0.8_vue@3.5.13_typescript@5.7.3___bc5a7fcb3abc4a847cdd271c57237c70/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
  }
}
